### ISSUE TITLE
Version 1.0 release

### ISSUE THREAD

**Issue by shirnschall** [DHL-ASC/DHL-LinAlg#16]
### Proposed new feature or change:

Version 1.0 release
- Merge active branches into main

**Comment by erdieee** [comment]
Why not start with version 0.0.1? See https://py-pkgs.org/07-releasing-versioning.html

**Comment by shirnschall** [comment]
The link you posted is inline with how I would do versioning (major.minor.patch) and it states:

"Major release (0.1.0 -> 1.0.0): release 1.0.0 is typically used for the first stable release of your package.".

Thus the first stable release should be v1.0.0
