### ISSUE TITLE
ENH: Documentation

### ISSUE THREAD

**Issue by erdieee** [DHL-ASC/DHL-LinAlg#17]
### Duplication check

- [X] I checked the existing feature requests.

### Proposed new feature or change:

The documentation needs refactoring.  The following changes should be addressed:
- Change the name of the package
- Installation guide
- Add some examples 
- Api reference (Matrix and Vector)

Not necessary at the moment:
- Contribution guide/ installation for own development
- Changelog for future versions

**Comment by shirnschall** [comment]
Also add speed comparison graphs with other libraries like e.g. eigen
